# Generated by Django 2.2 on 2019-05-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('modelo', models.CharField(max_length=8)),
                ('contador', models.IntegerField()),
                ('etiqueta', models.CharField(max_length=15)),
                ('galpao', models.CharField(max_length=2)),
                ('coluna', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
