# Generated by Django 2.2 on 2019-05-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='galpao',
            field=models.CharField(max_length=3),
        ),
    ]
