# Generated by Django 2.2 on 2019-04-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='etiqueta',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
