# Generated by Django 2.2 on 2019-05-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
