# Generated by Django 2.2 on 2019-04-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0002_printer_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='id',
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
