# Generated by Django 2.2 on 2019-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0002_auto_20190514_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='contador',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='modelo',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
