# Generated by Django 2.2 on 2019-04-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0003_auto_20190415_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='contador',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial',
            field=models.CharField(max_length=20),
        ),
    ]
