# Generated by Django 2.2 on 2019-04-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0004_auto_20190415_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='contador',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
