# Generated by Django 2.2 on 2019-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0006_auto_20190415_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
