# Generated by Django 2.2 on 2019-04-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0007_auto_20190415_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='local',
        ),
        migrations.AddField(
            model_name='printer',
            name='coluna',
            field=models.CharField(default='coluna', max_length=20),
        ),
        migrations.AddField(
            model_name='printer',
            name='galpao',
            field=models.CharField(default='galpao', max_length=2),
            preserve_default=False,
        ),
    ]
