# Generated by Django 2.2 on 2019-04-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0008_auto_20190418_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='coluna',
            field=models.CharField(max_length=20),
        ),
    ]
