# Generated by Django 2.2 on 2019-05-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressora', '0009_auto_20190418_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial',
            field=models.CharField(max_length=20),
        ),
    ]
